In [1]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
from IPython.display import display # Allows the use of display() for DataFrames

# Pretty display for notebooks
%matplotlib inline

# Set a random seed
import random
random.seed(42)

# Load the dataset
in_file = 'titanic_data.csv'
full_data = pd.read_csv(in_file)

# Print the first few entries of the RMS Titanic data
display(full_data.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Clean The data

In [2]:
outcomes = full_data.Survived
print(outcomes.shape)
features_raw  = full_data.drop("Survived", axis=1)
#display(features_raw.head())
#display(features_raw.describe())

(891,)

Pre Process the data, clean unnecessary columns and one hot encoding

In [3]:
# Removing the names
features_no_names = features_raw.drop(['Name'], axis=1)


#display(features.head())
#isplay(features.describe())

#isplay(features.describe())

In [4]:
# One-hot encoding
features = pd.get_dummies(features_no_names)

In [5]:
features = features.fillna(0.0)

In [6]:
display(features)

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Ticket_110152,Ticket_110413,...,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Embarked_C,Embarked_Q,Embarked_S
0,1,3,22.0,1,0,7.2500,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2,1,38.0,1,0,71.2833,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,3,26.0,0,0,7.9250,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,1,35.0,1,0,53.1000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,5,3,35.0,0,0,8.0500,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
5,6,3,0.0,0,0,8.4583,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
6,7,1,54.0,0,0,51.8625,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
7,8,3,2.0,3,1,21.0750,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,9,3,27.0,0,2,11.1333,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,10,2,14.0,1,0,30.0708,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10,11,3,4.0,1,1,16.7000,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
11,12,1,58.0,0,0,26.5500,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,13,3,20.0,0,0,8.0500,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
13,14,3,39.0,1,5,31.2750,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
14,15,3,14.0,0,0,7.8542,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,16,2,55.0,0,0,16.0000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,17,3,2.0,4,1,29.1250,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
17,18,2,0.0,0,0,13.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
18,19,3,31.0,1,0,18.0000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,20,3,0.0,0,0,7.2250,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
20,21,2,35.0,0,0,26.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
21,22,2,34.0,0,0,13.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
22,23,3,15.0,0,0,8.0292,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,24,1,28.0,0,0,35.5000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
24,25,3,8.0,3,1,21.0750,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,26,3,38.0,1,5,31.3875,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,27,3,0.0,0,0,7.2250,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
27,28,1,19.0,3,2,263.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
28,29,3,0.0,0,0,7.8792,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
29,30,3,0.0,0,0,7.8958,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,2,21.0,1,0,11.5000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
862,863,1,48.0,0,0,25.9292,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
863,864,3,0.0,8,2,69.5500,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
864,865,2,24.0,0,0,13.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
865,866,2,42.0,0,0,13.0000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
866,867,2,27.0,1,0,13.8583,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
867,868,1,31.0,0,0,50.4958,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
868,869,3,0.0,0,0,9.5000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
869,870,3,4.0,1,1,11.1333,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
870,871,3,26.0,0,0,7.8958,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
871,872,1,47.0,1,1,52.5542,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
872,873,1,33.0,0,0,5.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
873,874,3,47.0,0,0,9.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
874,875,2,28.0,1,0,24.0000,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
875,876,3,15.0,0,0,7.2250,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
876,877,3,20.0,0,0,9.8458,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
877,878,3,19.0,0,0,7.8958,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
878,879,3,0.0,0,0,7.8958,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
879,880,1,56.0,0,1,83.1583,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
880,881,2,25.0,0,1,26.0000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
881,882,3,33.0,0,0,7.8958,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
882,883,3,22.0,0,0,10.5167,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
883,884,2,28.0,0,0,10.5000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
884,885,3,25.0,0,0,7.0500,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
885,886,3,39.0,0,5,29.1250,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
886,887,2,27.0,0,0,13.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
887,888,1,19.0,0,0,30.0000,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
888,889,3,0.0,1,2,23.4500,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
889,890,1,26.0,0,0,30.0000,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
890,891,3,32.0,0,0,7.7500,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

Train the Model

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(features,outcomes, test_size=0.2,random_state=42)

In [8]:
print(X_train.shape)
print(y_train.shape)

(712, 839)
(712,)

In [9]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

In [11]:
# Calculate the accuracy
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)

The training accuracy is 1.0
The test accuracy is 0.8156424581005587

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.model_selection import ShuffleSplit

In [13]:
    dt_range = range(1, 10)
    params = dict(max_depth=dt_range)
    print(params)
    scoring_fnc = make_scorer(accuracy_score)

{'max_depth': range(1, 10)}

In [14]:
cv_sets = ShuffleSplit(n_splits = 10, test_size = 0.20, random_state = 0)

In [22]:
classifier = DecisionTreeClassifier(min_samples_leaf=0.3,min_samples_split=3)

In [ ]:
classifier.fit(X_train, y_train)

In [16]:
#grid = GridSearchCV(classifier, params, cv=cv_sets, scoring=scoring_fnc)

In [21]:
#grid = grid.fit(X_train, y_train)

In [18]:
#bestEstimate = grid.best_estimator_

In [19]:
y_grid_test_predicted =classifier.predict(X_test)

In [20]:
print(accuracy_score(y_test,y_grid_test_predicted))

0.7821229050279329